/***************************************************************************
//
// ONSIP.CPP
//
// TAPI Service provider for TSP++ version 3.0
// Main TAPI Service Provider shell
//
// Copyright (C) 2009 Junction Networks
// All rights reserved
//
// Generated by the TSPWizard © 2009 JulMar Technology, Inc.
// 
/***************************************************************************/

/*-------------------------------------------------------------------------------*/
// INCLUDE FILES
/*-------------------------------------------------------------------------------*/
#include "stdafx.h"
#include "OnSip.h"
#include <atlbase.h>
#include "OnSipSettings.h"

/*-------------------------------------------------------------------------------*/
// CONSTANTS AND GLOBALS
/*-------------------------------------------------------------------------------*/
COnSipServiceProvider theSP;

/*-------------------------------------------------------------------------------*/
// RTTI overrides of TSP++ objects
/*-------------------------------------------------------------------------------*/
DECLARE_TSPI_OVERRIDE(COnSipDevice);
DECLARE_TSPI_OVERRIDE(COnSipLine);

/*****************************************************************************
** Procedure:  COnSipServiceProvider::COnSipServiceProvider
**
** Arguments:  void
**
** Returns:    void
**
** Description:  This is the constructor for the provider object.  It
**               is responsible for initializing the UI.DLL name and the
**               provider manufacturer names.  In additional, any overrides
**               of class objects should be performed here.
**
*****************************************************************************/
COnSipServiceProvider::COnSipServiceProvider() : 
	CServiceProvider(_T("OnSipUI.DLL"),		// Name of UI DLL
					 PROVIDER_NAME,
					 TAPIVER_21)
{   
	// Setup our line device and phone device object override.
	SetRuntimeObjects (
		"COnSipDevice",	// Device override 
		"COnSipLine",		// Line override

		NULL,						// Address override

		NULL,						// Call override

		NULL,						// Conference call override

		NULL);						// Phone override

	// Set the general app debug level
	Logger::SetWin32Level( OnSipSettings::GetDebugLevel() );
	Logger::log_debug("COnSipServiceProvider::COnSipServiceProvider  tspDebugLevel=%lx", OnSipSettings::GetTSPDebugLevel() );
	// Set the TSP debug level
	SetTraceLevel( OnSipSettings::GetTSPDebugLevel() );

}// COnSipServiceProvider::COnSipServiceProvider

/*****************************************************************************
** Procedure:  COnSipServiceProvider::TraceOut
**
** Arguments:  'strBuff' - Buffer to output
**
** Returns:    void
**
** Description:  This is called on an idle thread to save off the debug
**               contents to persistent storage.
**
*****************************************************************************/
//virtual
void COnSipServiceProvider::TraceOut(const TString& strBuff)
{
	tstring str = Strings::trim( strBuff.c_str() );
	Logger::log_debug( "TSP:%s", str.c_str() );
}


// Override the version from CServiceProvider since it does not appear to work very well.
//
// This is the main function which converts a dialable number from TAPI into the
// displayed canonical format.  It utilizes the below two routines.
//virtual 
TString COnSipServiceProvider::ConvertDialableToCanonical (LPCTSTR pszNumber, DWORD /*dwCountry*/, bool /*fInbound*/)
{
	// Return back unmodified
	if ( pszNumber == NULL )
		return _T("");
	return TString( pszNumber );
}


