/***************************************************************************
//
// Config.h
//
// TAPI Service provider for TSP++ version 3.0
// Configuration dialog
//
// Copyright (C) 2009 Junction Networks
// All rights reserved
//
// Generated by the TSPWizard © 2009 JulMar Technology, Inc.
// 
/***************************************************************************/

#include "afxwin.h"
#if !defined(AFX_CONFIG_H__CDF1605B_B424_11D2_AD1B_DCB70C000000__INCLUDED_)
#define AFX_CONFIG_H__CDF1605B_B424_11D2_AD1B_DCB70C000000__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

/***************************************************************************
** CConfigDlg
**
** This dialog is a sample configuration dialog for the service provider.
**
***************************************************************************/
class CConfigDlg : public CDialog
{
// Dialog Data
protected:
	//{{AFX_DATA(CConfigDlg)
	enum { IDD = IDD_CONFIG_DIALOG };
	// NOTE: the ClassWizard will add data members here
	//}}AFX_DATA

// Construction
public:
	CConfigDlg(CWnd* pParent = NULL);	// standard constructor
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CConfigDlg)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);	// DDX/DDV support
	//}}AFX_VIRTUAL
	
// Implementation
protected:
	CEdit m_txtPhoneNumber;
	CEdit m_txtSipAddress;
	CEdit m_txtPassword;

	CString m_phoneNumber;
	CString m_sipAddress;
	CString m_passWord;

	// Generated message map functions
	//{{AFX_MSG(CConfigDlg)
	virtual BOOL OnInitDialog();
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
public:
	afx_msg void OnBnClickedOk();

	void SetValues(const tstring& phoneNumber,const tstring& sipAddress,const tstring& passWord);
	void GetValues(tstring& phoneNumber,tstring& sipAddress,tstring& passWord);
public:
	afx_msg void OnBnClickedTest();
public:
	CStatic m_lblTesting;
public:
	CButton m_OK;
public:
	CButton m_Cancel;
public:
	CButton m_Testing;
public:
	CStatic m_lblTitle;
public:
	CStatic m_lblInfo;
public:
	afx_msg BOOL OnSetCursor(CWnd* pWnd, UINT nHitTest, UINT message);
public:
	bool m_bWaitCursor;
public:
	CStatic m_version;
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CONFIG_H__CDF1605B_B424_11D2_AD1B_DCB70C000000__INCLUDED_)
